### ISSUE TITLE
org.odata.internal.TypeConverter class provide conversion of limited data type

### ISSUE THREAD

**Issue by GoogleCodeExporter** [johnkajava/odata4j#280]
```
What steps will reproduce the problem?
1. Create simple JPA entity having Long Id for primary key
2. Access this entity using it primary key like this url/Entity(id)
3.

JAX-WS Training in Chennai. Java SE Training Institutes in Chennai. Java EE training Institutes in Chennai. Java Persistence API Training Institutes in Chennai.

What is the expected output? What do you see instead?
Got an error stated that 'invalid key type'. upon deubbing found that in 
TypeConverter class value of desireClass attribute is 
javax.jdo.identity.LongIdentity and there is no if block to handle this type.

What version of the product are you using? On what operating system?
odata4j0.7

Please provide any additional information below.

Java Web Services Training in Chennai. Java Training in Chennai. Java Training Institutes in Chennai. JAX-WS Training in Chennai.
```

Original issue reported on code.google.com by `waqas.tw...@gmail.com` on 21 May 2014 at 5:33

**Comment by johnkajava** [comment]
<a href="http://wisenitsolutions.com/IT-Courses/Java-Web-Services-Training" title="Java Web Services Online Training">Java Web Services Online Training</a> | <a href="http://wisenitsolutions.com/IT-Courses/Java-Web-Services-Training" title="Web Services Course">Web Services Course</a> | <a href="http://wisenitsolutions.com/IT-Courses/Java-Web-Services-Training" title="Web Services Training Courses">Web Services Training Courses</a> | <a href="http://wisenitsolutions.com/IT-Courses/Java-Web-Services-Training" title="Java Web Services Training in Chennai">Java Web Services Training in Chennai</a> | <a href="http://wisentechnologies.com/it-courses/java-training.aspx" title="Java Course in Chennai">Java Course  in Chennai</a> | <a href="http://wisentechnologies.com/it-courses/java-training.aspx" title="Java Training Institutes in Chennai">Java Training  Institutes in Chennai</a> |  <a href="http://wisentechnologies.com/it-courses/java-training.aspx" title="Java Training in Chennai">Java Training  in Chennai</a>
